name: Check Markdown Links

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    env:
      ZENML_DEBUG: 1
      ZENML_ANALYTICS_OPT_IN: false
    steps:
    - uses: actions/checkout@main
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: .github/workflows/markdown_check_config.json
    